export enum ConversationStage {
  GREETING = "GREETING",
  QUALIFYING = "QUALIFYING",
  INFORMATION = "INFORMATION",
  PLAN_RECOMMENDATION = "PLAN_RECOMMENDATION",
  SCHEDULING = "SCHEDULING",
  PENDING_HUMAN = "PENDING_HUMAN",
  COMPLETED = "COMPLETED"
}
