export enum InquiryStatus {
  NEW = "NEW",
  QUALIFIED = "QUALIFIED",
  PENDING_FOLLOWUP = "PENDING_FOLLOWUP",
  APPOINTMENT_TENTATIVE = "APPOINTMENT_TENTATIVE",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  CLOSED = "CLOSED"
}
