export enum NotificationEventType {
  LEAD_CREATED = "LEAD_CREATED",
  LEAD_UPDATED = "LEAD_UPDATED",
  APPOINTMENT_REQUESTED = "APPOINTMENT_REQUESTED",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
}
